In [2]:
import pandas as pd

df_ranking_training = pd.read_csv('results/ICLR20/ComplEx/FB237/fb237_er_error_analysis_ranking_train.csv')
df_ranking_training['eval_type'] = 'train'
df_ranking_training.head(2)

,id,name_subjects,name_relation,name_objects,relation_type,triplet,po_to_s_hybrid,po_to_s_standard,predicted_object_hybrid,predicted_object_scores_hybrid,...,predicted_relation_standard,predicted_subject_hybrid,predicted_subject_score_hybrid,predicted_subject_score_standard,predicted_subject_standard,so_to_p_hybrid,so_to_p_standard,sp_to_o_hybrid,sp_to_o_standard,eval_type
0,0,Dominican Republic,/location/country/form_of_government,Republic,M-N,Dominican Republic | /location/country/form_of...,0,0,['Republic' 'Democracy' 'Presidential system' ...,"[10.101889610290527, 9.739956855773926, 8.3898...",...,['/location/country/form_of_government'\n '/ed...,['Gabon' 'Tanzania' 'Cape Verde' 'Burundi' 'Be...,"[10.939971923828125, 10.905258178710938, 10.77...","[12.28516674041748, 12.251543998718262, 12.203...",['Yemen' 'Benin' 'Zambia' 'Somalia' 'Togo'],0,0,0,0,train
1,1,Mighty Morphin Power Rangers,/tv/tv_program/regular_cast./tv/regular_tv_app...,Wendee Lee,1-N,Mighty Morphin Power Rangers | /tv/tv_program/...,0,0,"['Johnny Yong Bosch' 'Wendee Lee' ""Liam O'Brie...","[14.309209823608398, 14.113879203796387, 7.993...",...,['/location/hud_county_place/place'\n '/educat...,['Mighty Morphin Power Rangers' 'Power Rangers...,"[14.113032341003418, 8.514370918273926, 7.8727...","[19.89518165588379, 14.366918563842773, 11.103...",['Mighty Morphin Power Rangers' 'Power Rangers...,0,1,0,0,train

In [27]:
df_similar_so = pd.read_csv('results/ICLR20/ComplEx/FB237/fb237_error_analysis_relations_in_similar_so_all.csv')
df_similar_so['name_relation'] = df_similar_so.name_relation.map(lambda x: ast.literal_eval(x))
df_similar_so.head(2)

,so_pair,name_relation,eval_type,relation_type,counts,is_similar,so_to_p_standard_Hybrid,so_to_p_standard_ER,so_to_p_hybrid_Hybrid,so_to_p_hybrid_ER,...,predicted_relation_hybrid_Hybrid,predicted_relation_hybrid_ER,euclidean_dist_standard_Hybrid,euclidean_dist_standard_ER,euclidean_dist_hybrid_Hybrid,euclidean_dist_hybrid_ER,cosine_sim_standard_Hybrid,cosine_sim_standard_ER,cosine_sim_hybrid_Hybrid,cosine_sim_hybrid_ER
0,"(500) Days of Summer, _ ,2009 Sundance Film Fe...","(/film/film/film_festivals, /film/film/release...",train,"('M-1', 'M-1')","(280, 262)",True,"(0, 0)","(1, 0)","(0, 0)","(0, 0)",...,/film/film/film_festivals,/film/film/film_festivals,14.358633,3.434402,12.351998,12.388579,0.668023,0.504762,0.657049,0.674233
1,"(500) Days of Summer, _ ,United Kingdom",(/film/film/distributors./film/film_film_distr...,train,"('M-1', 'M-N')","(168, 14121)",False,"(0, 1)","(6, 13)","(0, 0)","(0, 0)",...,/film/film/release_date_s./film/film_regional_...,/film/film/release_date_s./film/film_regional_...,13.335735,4.617963,15.251811,14.911905,0.589967,0.234951,0.340485,0.283289